repos:
  - repo: https://github.com/biomejs/pre-commit
    rev: "v0.6.1"  # 使用するバージョンを指定してください
    hooks:
      - id: biome-check
        additional_dependencies: ["@biomejs/biome@1.9.4"]
        args: ["--apply"]  # 自動修正を有効化
